version: "3.7"

services:

  fever-dashboard:
    build: .
    container_name: fever-dashboard
    restart: always
    ports:
      - 80:80

#networks:
#  default:
#    external:
#      name: guardian-network
