version: "3.7"

services:

  fever-dashboard:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: fever-dashboard
    restart: always

networks:
  default:
    external:
      name: guardian-network

